version: '3.8'

services:
  api:
    image: ndissanayake/mern_app_backend_new:latest
    ports: 
      - '4000:4000'
    networks:
      - restaurant
    depends_on:
      - mongo

  client:
    image: ndissanayake/mern_app_frontend_new:latest
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - restaurant

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - restaurant
    volumes:
      - mongo-data:/data/db
    
networks:
  restaurant:
    driver: bridge

volumes:
  mongo-data:
    driver: local